version: "3"

services:
  mongo:
    image: mongo:4.0.11
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: mongotest/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
